[env]
# Wind options: ['none', 'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW']
wind = 'E'  
# The initial fraction of the forest occupied by trees.
forest_fraction = 0.90
# Define fire spread probability (ignored when wind is not 'none')
fire_spread_prob = 0.65
# Define probability that the fire burns outward against the wind
up_wind_spread_prob = 0.15
# Define the overall relative fire speed
fire_speed = 0.8
# Forest size (number of cells in x and y directions).
grid_size = 200
# Define the number of ignition points (1 will set a central ignition)
ignition_points = 1

[agent]


[animation]
# true if the animation should repeat before stopping
repeat = false
# set the time interval between frames in the animation
interval = 30  #ms
# true in order to show the animation after the episode ends 
save_anim = true
# true in order to save the animation to disk
show_anim = true